version: '3'
services:
  linklist:
    image: linklist_image
    build:
      context: .
    container_name: linklist_app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "7777:8000"