# Generated by Django 5.0.4 on 2024-04-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_alter_link_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='short_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
